#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require _DIR_.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once _DIR_.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);